name: Test Fybrik
on: 
  workflow_dispatch:
    inputs:
      kind-version:
        required: true
        default: 'kind24'
        type: choice
        options:
        - kind19
        - kind20
        - kind21
        - kind22
        - kind23
        - kind24
      fybrik-version:
        required: true
        default: '1.3.0'
      module-version:
        required: true
        default: 'master'
      cert-manager-version:
        required: true
        default: '1.6.2'

env:
  GO_VERSION: 1.17

jobs:
  test-module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: install tools
      run: make install-tools
    - name: run test
      run: tests/test_fybrik.sh ${{ github.event.inputs.kind-version }} ${{ github.event.inputs.fybrik-version }} ${{ github.event.inputs.module-version }} ${{ github.event.inputs.cert-manager-version }}
