name: Test Fybrik
on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.19

jobs:
  test-module:
    runs-on: ubuntu-latest
    env:
      kindVersion: 'kind25'
      fybrikVersion: 'master'
      moduleVersion: 'master'
      certManagerVersion: '1.6.2'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: install tools
      run: make install-tools
    - name: run test
      run: tests/test_fybrik.sh $kindVersion $fybrikVersion $moduleVersion $certManagerVersion
